/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Alumno;
import Modelo.AlumnoData;
import Modelo.Conexion;
import Modelo.Cursada;
import Modelo.CursadaData;
import Modelo.Materia;
import Modelo.MateriaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author melid
 */
public class VistaAlumnosXMateria extends javax.swing.JInternalFrame {

    private Conexion conexion;
    private DefaultTableModel modelo;
    private ArrayList <Cursada> listaCursada;
    private ArrayList <Materia> listaMaterias;
    private ArrayList <Alumno> listaAlumnos;
    private CursadaData cursadaData;
    private MateriaData materiaData;
    private AlumnoData alumnoData;
    
    
    
    public VistaAlumnosXMateria() throws SQLException {
        initComponents();
        
        try {
            conexion = new Conexion ("jdbc:mysql://localhost/universidad.g1", "root", "");
            modelo = new DefaultTableModel();
            
            cursadaData = new CursadaData(conexion);
            listaCursada=(ArrayList)cursadaData.obtenerCursada();
            
            materiaData = new MateriaData(conexion);
            listaMaterias = (ArrayList)materiaData.obtenerMaterias();
            
            alumnoData = new AlumnoData (conexion);
            listaAlumnos=(ArrayList)alumnoData.obtenerAlumnos();
            
            cargarMaterias();
            armaCabeceraTabla();
            cargarDatos();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaAlumnosXMateria.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMaterias = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlumnos = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("~Listado de Alumnos Por Materia~");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Materia:");

        cbMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMateriasActionPerformed(evt);
            }
        });

        tAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarMaterias(){
        
      for (Materia item:listaMaterias){ 
          cbMaterias.addItem(item);
        
        
    }
    } 
    private void armaCabeceraTabla(){
        
        ArrayList <Object> columns = new  ArrayList <Object> ();
        columns.add("ID");
        columns.add("MATERIA");
        columns.add("NOTA");
        
        for(Object it:columns){
        
        modelo.addColumn(it);
        }
        
        tAlumnos.setModel(modelo);
        
       }
    
    public void borrarFilasTabla(){
        
        int a = modelo.getRowCount()-1;
        for(int i=a; i>=0; i--){
            
        modelo.removeRow(i);
        
        }
    }
    
    
    public void cargarDatos(){
     
        borrarFilasTabla();
        
        Materia mat = (Materia)cbMaterias.getSelectedItem();
        for (Cursada m:listaCursada){
       if (m.getMateria().getIdMateria()== mat.getIdMateria()){
           
           modelo.addRow(new Object []{m.getAlumno().getIdAlumno(),m.getAlumno().getNombre(),m.getNota()});
           
           
           
       }
       }
    }
    private void cbMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMateriasActionPerformed

      cargarDatos();






        // TODO add your handling code here:
    }//GEN-LAST:event_cbMateriasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Materia> cbMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tAlumnos;
    // End of variables declaration//GEN-END:variables
}
